<?php

/**
 * @file
 * Code for the GSB Feature Person Display feature.
 */

include_once 'gsb_feature_person_display.features.inc';

/**
 * Implements hook_entity_info_alter().
 */
function gsb_feature_person_display_entity_info_alter(&$entity_info) {
  $entity_info['fieldable_panels_pane']['bundles']['gsb_person_fpp'] = array(
    'label' => t('Add GSB Persons'),
    'pane category' => t('GSB Person FPP'),
    'pane top level' => TRUE, // set to true to make this show as a top level icon
    'pane icon' => drupal_get_path('module', 'panopoly_widgets') . '/images/icon_text.png',
    'admin' => array(
      'path' => 'admin/structure/fieldable-panels-panes/manage/%fieldable_panels_panes_type',
      'bundle argument' => 4,
      // Note that this has all _ replaced with - from the bundle name.
      'real path' => 'admin/structure/fieldable-panels-panes/manage/gsb-person-fpp',
      'access arguments' => array('administer fieldable panels panes'),
    ),
  );
}

/**
 * Implements hook_preprocess_HOOK() for theme_fieldable_panels_pane().
 */
function gsb_feature_person_display_preprocess_fieldable_panels_pane(&$variables) {
  if (!isset($variables['elements']['#bundle']) || $variables['elements']['#bundle'] != 'gsb_person_fpp') {
    return;
  }

  $pane = $variables['elements']['#element'];
  $display_style = field_get_items('fieldable_panels_pane', $pane, 'field_display_style');
  if (!empty($display_style['0']['value']) && $display_style['0']['value'] == 'person-grid-view') {
    $display_id = 'grid';
  }
  else {
    $display_id = 'list';
  }

  if ($view_output = views_embed_view('gsb_person_fpp_view', $display_id, $pane->fpid)) {
    $variables['fields'] = $view_output;
  }
}
